[files]
extend-exclude = [
    "*env*",
    "**/typos/**/*"
]

# [type.vimscript.extend-identifiers]
# enew = "enew"

[type.vimscript.extend-words]
enew = "enew"
matchend = "matchend"

[type.lua.extend-words]
enew = "enew"
matchend = "matchend"

[type.rust.extend-words]
ratatui = "ratatui"
