gui:
  theme:
    selectedLineBgColor:
      # - default
      - reverse
  showFileTree: false
  useHunkModeInStagingView: false
keybinding:
  files:
    # swap default bindings
    commitChanges: "C"
    commitChangesWithEditor: "c"
customCommands:
  - key: "P"
    context: "global"
    command: "git push-with-check"
# there is blinking bug https://github.com/jesseduffield/lazygit/issues/1302
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --color-only
