KeyBind:
  down:
      - "Enter"
      - "Down"
      - "ctrl+N"
      - "j"
  up:
      - "Up"
      - "ctrl+p"
      - "k"
  left:
      - "left"
      - "h"
  right:
      - "right"
      - "l"
  top:
      - "Home"
      - "0"
  jump_target:
      - "J"
  page_down:
      - "PageDown"
      - "ctrl+f"
  follow_mode:
      - "ctrl+v"
  next_section:
      - "Tab"
  previous_section:
      - "Backtab"
  help:
      - "?"
      - "ctrl+alt+c"
      - "ctrl+f1"
